name: Python Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Теперь steps находятся внутри job 'test'
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

             
      - name: докер поднимаем
        run: docker build -t myapp .|
          
        
      - name: тесты внутри контейнера
        run: docker run myapp
         
         
      - name: CD процесс (Деплой)
        run: |
          # Учти, что папка ../staging живет только внутри этого раннера
          mkdir -p ../staging
          cp -r . ../staging/

